### ISSUE TITLE
Dealing with credentials

### ISSUE THREAD

**Issue by sckott** [getwilds/sixtyfour#10]
I was looking at addressing [this comment](https://github.com/fhdsl/sixtyfour/pull/3/files/646483fd4f9fd8593a0c9109c6ad6980c9825233#diff-8acc7261c62302a60dae31825c43ffed4ba32af22ec6e137d5aff5640e27ffff) about checking an env var, and then realized that paws has a number of different ways to find user auth details. So we can't just look for env vars. 

However, we still need to have access to some credentials for our own use within this package. e.g, the link above where we want to get the aws region the user has set in their creds. 

We can hack getting access key and secret key via calling this anonymous function in an environment, but that's hacky for sure. and it doesn't list the aws region either

```r
s3 <- paws::s3()
s3$.internal$config$credentials$provider[[2]]()
```

Perhaps there's a way in paws to fetch user creds somehow, and I just haven't found it yet

**Comment by seankross** [comment]
Some ideas that come to mind:

- Should we use something like https://github.com/r-lib/oskeyring? 
- Should we make a mini aws https://github.com/r-lib/gitcreds situation?
- Should we just force the user to set some env vars?

**Comment by sckott** [comment]
Thanks! This feels like a situation where we should go with the dead simplest solution first, and add complexity if needed. That is:

- simple solution: make users set env vars in addition to whatever other aws creds method they have (if already using env vars then all set)
- more complex: add a package dependency e.g., `oskeyring` or `gitcreds`

**Comment by seankross** [comment]
I totally agree.

**Comment by sckott** [comment]
Lets stick with whatever `paws` does for now and think about solutions when/if we hit problems

**Comment by sckott** [comment]
Allow users to set their AWS account within exported functions?

Possibly via some helper fxn, ideally not through every function, which would add extra work for everyone. 

e.g., `costexplorer` has

```r
costexplorer(
  config = list(),
  credentials = list(),
  endpoint = NULL,
  region = NULL
)
```

We initialize that list of functions for cost explorer ourselves - we could have helper funs to allow users to set creds so whenever it initializes they are used
