### ISSUE TITLE
build out remainder of file fxns

### ISSUE THREAD

**Issue by sckott** [getwilds/sixtyfour#13]
see also #3  and #11

**Comment by sckott** [comment]
what we have now on main

- `aws_file_upload`
- `aws_file_download`
- `aws_file_attr`
- `aws_file_exists`

possible fxns to add:

- copy: use cases could cover copying files between buckets. and copying from s3 to local and local to s3. if we did this then the upload and download fxns above could stay but we'd just wrap the copy fxn to do those more narrow use cases
- rename, a move action under the hood
- delete
- get a presigned url for a file

related to #9 -  `s3fs` also builds on top of `paws` - we could use `s3fs` for file functionality under the hood here instead of using `paws`  - we'd be using `paws` indirectly. however, that would i think be such a thin layer on top of `s3fs` that we might as well just say go use `s3fs`. whereas it does make sense to build a layer on top of `paws` because of it's complexity. 

@seankross Any thoughts on functions around files that would solve data DCC use cases particularly well? Are we recreating the wheel here wrt file functions?

**Comment by sckott** [comment]
@seankross I reworked file fxns to use `s3fs` under the hood. still working on some in the above list. Any thoughts on my question above about DCC use cases?

**Comment by seankross** [comment]
- `copy` makes sense to me, it would be friendliest if it wrapped upload and download but real use would be for copying between buckets.
- `rename` and `delete` I think are both required
- get a presigned url for a file: that would be so cool! I feel like this is more of a stretch goal or a "let's show off" goal if you think it's not that big of a lift.

**Comment by sckott** [comment]
Thanks for those thoughts. 

Any thoughts on my question above about DCC use cases?

**Comment by seankross** [comment]
I think these functions cover the most common DCC use cases around files, the real finesse on that front is going to be in how we handle permissions.
