### ISSUE TITLE
Temporary accounts for testing?

### ISSUE THREAD

**Issue by sckott** [getwilds/sixtyfour#16]
It'd be perfect if there was a way to spin up a temporary top level S3 account to run a test suite, then clean it up afterwards INSTEAD OF messing with our real account. 

Though unit tests I think will be using cached fixtures anyway, so on CI won't be hitting our real buckets.

**Comment by seankross** [comment]
@vortexing Could I put a test AWS account on a pro-card, assuming that account is only for software testing purposes? Or should I go through IT to get an account?

**Comment by sckott** [comment]
Thanks for asking if we can do that Sean. 

Other options might be to:

- Run package checks/tests against fixtures, as mentioned above
- Use something like https://github.com/localstack/localstack ([gh actions docs for it](https://docs.localstack.cloud/user-guide/ci/github-actions/)) to run checks/tests against - have not tried it yet

**Comment by sckott** [comment]
## notes on minio:

```
# start, ctrl-c to exit
minio server start --console-address :9090
```

## notes on localstack

```
# start, , ctrl-c to exit
localstack start
```

then followed https://docs.localstack.cloud/user-guide/aws/redshift/ to get a local redshift cluster. haven't tried using it yet

**Comment by sckott** [comment]
Oopsy, localstack is hecka expensive. Look around for something else

**Comment by seankross** [comment]
Hey Scott, we have clearance to create an account. Will discuss when I return if that's okay.

**Comment by sckott** [comment]
Sounds good

**Comment by sckott** [comment]
yes
