### ISSUE TITLE
How to handle data from paws functions

### ISSUE THREAD

**Issue by sckott** [getwilds/sixtyfour#4]
The results of `paws` calls are generally named lists, sometimes nested.  What should we do to these data before giving back to users:

1. Just give them what we get back from `paws` - a named list, in most cases
2. Coerce named lists to an S3 object that summarizes the list and hides the full list underneath?
3. Coerce named lists to a vctrs object that summarizes the list and hides the full list underneath?
4. Coerrce named lists to tibbles?
5. Something else?

There's other cases where what we return is more clear cut. Eg.., in a fxn that checks if a bucket exists we give back a boolean

@seankross thoughts?

**Comment by seankross** [comment]
I think the best option is 4, and I think we should be very opinionated about what columns we pass back to users. Ideally they would be the columns that we believe would be most useful to users, including potential inputs to other sixtyfour functions.

**Comment by sckott** [comment]
Sounds good. The tricky bit is to make the parsing code robust to nested list craziness, but can do
