### ISSUE TITLE
aws_secrets_all errors when there are no secrets

### ISSUE THREAD

**Issue by seankross** [getwilds/sixtyfour#65]
On branch s3-iam

```r
aws_secrets_all()
```
```
Error in `relocate()`:
! Can't select columns that don't exist.
✖ Column `arn` doesn't exist.
Run `rlang::last_trace()` to see where the error occurred.
```

Probably the ideal is it returns an empty tibble (like when there are no buckets)

**Comment by sckott** [comment]
thanks. not specific to no secrets - was filtering to a certain element being present, but I dont think that's necessary, plus another fix

**Comment by sckott** [comment]
should be fixed
