### ISSUE TITLE
Billing: handle `RECORD_TYPE` via filter or group_by

### ISSUE THREAD

**Issue by ateucher** [getwilds/sixtyfour#72]
Love where this package is going, so nice to see a "humane" approach to interacting with AWS!

I am using the billing functions, which to this point I have been [rolling for myself](https://github.com/NASA-Openscapes/2i2cAccessPolicies/pull/13/files#diff-d5fb2d022a1c7396fdfb20f19d15a4241f431df996438ad4bd47e25f115e2566). The `aws_billing()` is great for its simplicity, and I wonder if it can be more generalizable. 

My specific use-case is that in our current account, all of our usage is paid for by credits as the usage occurs. By default, the cost explorer API returns net costs by time period aggregated over all charge types, so our net daily cost comes out as zero (== usage - credits). I can deal with this in two ways - add a `GroupBy` parameter so it groups by [`RECORD_TYPE`](https://docs.aws.amazon.com/awsaccountbilling/latest/aboutv2/manage-cost-categories.html#cost-categories-terms) (`list(Type = "DIMENSION", Key = "RECORD_TYPE")`), and then I can filter locally to just get usage records. Or I can add a `Filter` statement to the CE query to just get `RECORD_TYPE == "Usage"`, which is what [I am currently doing](https://github.com/NASA-Openscapes/2i2cAccessPolicies/blob/a57157190e92ee7871af3ac4f4e4ef042a03e17f/aws-usage-report/aws-usage-report.qmd#L120-L123).

Apparently only two values for `GroupBy` are allowed, and since [GroupBy already has two values in `billing_factory()`](https://github.com/getwilds/sixtyfour/blob/13aade6a2440a6b82d307d5d29cacaad350b0140/R/billing.R#L78-L81), I wonder if allowing a user to pass a filter in through `aws_billing()` to `aws_billing_raw()` would be desirable? It actually looks like the plumbing was started as there is an [unused `filter` argument](https://github.com/getwilds/sixtyfour/blob/13aade6a2440a6b82d307d5d29cacaad350b0140/R/billing.R#L140) already there. 

I'd be happy to start a PR if this would be of interest?

(PS Hey @sckott 👋! And @seankross - hopefully you don't start to regret asking me to kick the tires! 😉)

**Comment by sckott** [comment]
Thanks for kicking the tires Andy! 

Yeah, please submit a PR and we'll talk about it. I imagine @seankross does have a vision for the billing interface, so do chime in Sean if you have a feeling on this
