### ISSUE TITLE
Test mocks for Billing?

### ISSUE THREAD

**Issue by sckott** [getwilds/sixtyfour#76]
It'd be great to be able to run tests for our billing functions. However, we don't want to run tests against AWS, and Localstack only has the option in their PRO version, and Minio doesn't have it at all. 

We could make mocks using real requests and changing the data to random/etc. - though that would be tedious. 

As PR #73 has shown it'd be nice to have this in place, so a change to the code, especially a PR, can know if their changes break any existing functionality.

**Comment by sckott** [comment]
Perhaps the best thing to do is use `webmockr` to not have any real requests and supply the responses we want for each test as stubs. Done this in `proofr` as an example https://github.com/getwilds/proofr/blob/main/tests/testthat/helper-stubs.R

**Comment by sckott** [comment]
Working locally on branch `billing-stubs`

**Comment by seankross** [comment]
Webmockr plan sounds great

**Comment by sckott** [comment]
Thanks
