### ISSUE TITLE
Database functionality

### ISSUE THREAD

**Issue by sckott** [getwilds/sixtyfour#8]
### What kinds of functions do we want to provide

- Setup a simple database; make sane choices for users, with assumption that users needs are for basic data science tasks
- Change permissions for a database, table, or row
- Fetch a key to use to connect to a database, e.g.:

```r
rds <- paws::rds()
token <- rds$build_auth_token(endpoint, region, user)
# then token passed to DBI::dbConnect()
```

### Things we will leave as an exercise for the user

Everything else, but we SHOULD document in vignettes how to do certain things:

- Table management
- Simple queries

**Comment by seankross** [comment]
I think we need to include functionality for setting up a database. We should make as many sane choices for users as possible, and we should assume that users are going to use individual databases for basic data science tasks. Therefore any hyper-scale database functionality is out of scope

**Comment by sckott** [comment]
Okay, can include db setup function(s).

**Comment by sckott** [comment]
Working on this on branch `dbs` 

notes trying to sort out how to do these functions
- https://aws.amazon.com/blogs/opensource/getting-started-with-r-on-amazon-web-services/
- https://blog.davisvaughan.com/posts/2017-05-10-aws-rds-r/
- https://medium.com/analytics-vidhya/connecting-amazon-relational-database-with-r-d9b800e5efb0
- connecting with a python client https://docs.aws.amazon.com/redshift/latest/mgmt/python-connect-examples.html 
- sorting out connection failure https://docs.aws.amazon.com/redshift/latest/mgmt/connecting-refusal-failure-issues.html
- localstack docs for redshift https://docs.localstack.cloud/user-guide/aws/redshift/
